apiVersion: v1
data:
  # SERVICE-CRED-<uniquevalue>: `echo {"entityName":"db", "userName":"testuser","password":"testpwd"} | base64 -w 0`
  SERVICE-CRED-1: e2VudGl0eU5hbWU6ZGIsIHVzZXJOYW1lOnRlc3R1c2VyLHBhc3N3b3JkOnRlc3Rwd2R9Cg==
  # CERTS-<uniquevalue>: `echo '{"entityName":"customer-client", "certIndetifier":"capten1","caCert":"LS0tLS1CRUdJTiB", "cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JS", "key":"LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBL"}' | base64 -w 0`
  CERTS-1: eyJlbnRpdHlOYW1lIjoiY3VzdG9tZXItY2xpZW50IiwgImNlcnRJbmRldGlmaWVyIjoiY2FwdGVuMSIsImNhQ2VydCI6IkxTMHRMUzFDUlVkSlRpQiIsICJjZXJ0IjogIkxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTIiwgImtleSI6IkxTMHRMUzFDUlVkSlRpQlNVMEVnVUZKSlZrRlVSU0JMIn0K
  #GENERIC-<uniquevalue>: `echo '{"credentialType":"cluster","entityName":"astra", "certIndetifier":"authToken", "clusterId": "b7f1640e-5488-4fc4-9230-10f58e195e1a", "token":"AstraCS:dQOUGyLDrxBsLJUPbdRqzwDs:ce353d87f144c46d740b4889caa840c0325aa0f8bb20eef891c9eefba055132b"}' | base64 -w 0`
  GENERIC-1: eyJjcmVkZW50aWFsVHlwZSI6ImNsdXN0ZXIiLCJlbnRpdHlOYW1lIjoiYXN0cmEiLCAiY2VydEluZGV0aWZpZXIiOiJhdXRoVG9rZW4iLCAiY2x1c3RlcklkIjogImI3ZjE2NDBlLTU0ODgtNGZjNC05MjMwLTEwZjU4ZTE5NWUxYSIsICJ0b2tlbiI6IkFzdHJhQ1M6ZFFPVUd5TERyeEJzTEpVUGJkUnF6d0RzOmNlMzUzZDg3ZjE0NGM0NmQ3NDBiNDg4OWNhYTg0MGMwMzI1YWEwZjhiYjIwZWVmODkxYzllZWZiYTA1NTEzMmIifQo=

kind: Secret
metadata:
  name: vault-cred-sync-data1
  namespace: "<vault-cred-namespace>"
type: Opaque
# 