apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultcred.fullname" . }}
  labels:
    {{- include "vaultcred.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vaultcred.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vaultcred.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vaultcred.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: vault-secret
              mountPath: {{ .Values.vault.vaultMountPath }}
              readOnly: true
          
             
          env:
            - name: VAULT_ADDR
              value: {{ .Values.env.vaultAddress }}
            - name: VAULT_CACERT
              value: {{ .Values.env.vaultCACertPath }}
            - name: VAULT_TOKEN_PATH
              value: {{ .Values.env.vaultTokenPath }}
            - name: VAULT_READ_TIMEOUT
              value: {{ .Values.env.vaultReadTimeout }}
            - name: VAULT_MAX_RETRIES
              value: {{ .Values.env.vaultMaxRetries }}
            - name: VAULT_ADDR
              value: {{ .Values.env.vaultAddress }}
              
          ports:
            - name: http
              containerPort: 9098
              protocol: TCP
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      volumes:
        - name: vault-secret
          secret:
            secretName: {{ .Values.vault.secretName }}
      
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
