name: Helm Chart publish

on:
  push:
    paths:
      - 'charts/**'
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Sheril5"
          git config user.email "Sheril5@@gmail.com"

      - name: Add Helm repos
        run: |
          helm repo add tools https://kube-tarian.github.io/helmrepo-supporting-tools

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.token }}"
